version: "2"
services:
    roscore:
        build: ros_indigo
        privileged: true
        ports:
            - "5555:5555"
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - ${sourcedir}:/opt/source
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ${HOME}/.Xauthority:/root/.Xauthority
        command: /bin/bash -c '/opt/ros/indigo/env.sh bash --rcfile /etc/bashrc_ros -c \\"source /etc/bashrc_ros;env;roslaunch ar_demo ar_demo.launch\\"'


    webserver:
        build: python_webserver
        ports:
            - "5000:5000"
        volumes:
            - ${webdir}:/opt/source
        command: python webserver.py --host=roscore --port=5556 --webport=5000
        depends_on:
            - roscore
        links:
            - roscore
            
    interactive_shell:
        build: ros_indigo
        stdin_open: true
        tty: true
        links:
            - roscore
            - webserver
        environment:
            - DISPLAY=${DISPLAY}
            - ROS_MASTER_URI=http://roscore:11311/
        command: /bin/bash -c '/opt/ros/indigo/env.sh bash --rcfile /etc/bashrc_ros'
        depends_on:
            - webserver
            - roscore
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ${HOME}/.Xauthority:/root/.Xauthority
            - ${sourcedir}:/opt/source
            

